# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               sreekanth mahesala
tagline:             'toString(<i>thoughts</i>)'
description:         'I’m Sreekanth Mahesala, Senior Data Science Engineer @ <a href="http://www.staples.com">Staples</a>, this space will communicate my experiences with data science that have made a difference. Feel free to rant and rave, I’m open to criticism and a firm believer of disagreement - it’s the only way forward!'
url:                 www.mahesala.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sreekanth Mahesala
  url:               www.mahesala.com
  email:             sreekanth.mahesala@gmail.com

# Custom vars
version:             1.0.0

# Social Contacts
twitter_username:
github_username: 
linkedin_username: sreekanthmahesala
facebook_username: sreekanth.mc

# Gems
gems: [jekyll-paginate]

theme: jekyll-theme-minimal