# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty

# Setup
title:               sreekanth mahesala
tagline:             'toString(thoughts)'
description:         'I’m Sreekanth Mahesala, this space will communicate my experiences with data science that have made a difference. Feel free to rant and rave, I’m open to criticism and a firm believer of disagreement - it’s the only way forward!' 
url:
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sreekanth Mahesala
  url:
  email:             sreekanth.mahesala@gmail.com

# Custom vars
version:             1.0.0

# Social Contacts
twitter_username:
github_username: sreekanthmahesala
linkedin_username: sreekanthmahesala
facebook_username: sreekanth.mc

# Gems
gems: [jekyll-paginate]
